import api, { USE_MOCK_DATA } from "./api";

// Mock reports data
const MOCK_REPORTS = [
  {
    id: "1",
    title: "Monthly High-Risk Summary",
    type: "High-Risk Cases",
    date: "2024-11-01",
    status: "Completed",
    generatedBy: "Dr. Sarah Connor",
    size: "2.4 MB",
  },
  {
    id: "2",
    title: "Drug Safety Audit - Q3 2024",
    type: "Drug Safety",
    date: "2024-10-15",
    status: "Completed",
    generatedBy: "System",
    size: "1.8 MB",
  },
  {
    id: "3",
    title: "Patient Outcomes Report",
    type: "Patient Outcomes",
    date: "2024-09-30",
    status: "Completed",
    generatedBy: "Dr. John Smith",
    size: "3.2 MB",
  },
];

/**
 * Reports Service
 * Handles report generation and management
 */
const reportsService = {
  /**
   * Get all reports
   * @param {Object} filters - Filter options
   * @returns {Promise<Array>} List of reports
   */
  async getReports(filters = {}) {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 400));

      let reports = [...MOCK_REPORTS];

      // Apply filters
      if (filters.type) {
        reports = reports.filter((r) => r.type === filters.type);
      }

      if (filters.startDate) {
        reports = reports.filter(
          (r) => new Date(r.date) >= new Date(filters.startDate)
        );
      }

      if (filters.endDate) {
        reports = reports.filter(
          (r) => new Date(r.date) <= new Date(filters.endDate)
        );
      }

      return reports;
    }

    const params = new URLSearchParams(filters).toString();
    return api.get(`/reports${params ? `?${params}` : ""}`);
  },

  /**
   * Get report by ID
   * @param {string} id - Report ID
   * @returns {Promise<Object>} Report details
   */
  async getReport(id) {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 300));
      const report = MOCK_REPORTS.find((r) => r.id === id);
      if (!report) throw new Error("Report not found");
      return report;
    }

    return api.get(`/reports/${id}`);
  },

  /**
   * Generate custom report
   * @param {Object} reportConfig - Report configuration
   * @returns {Promise<Object>} Generated report
   */
  async generateReport(reportConfig) {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 1500));

      const newReport = {
        id: String(MOCK_REPORTS.length + 1),
        title: reportConfig.title || "Custom Report",
        type: reportConfig.type || "Custom",
        date: new Date().toISOString().split("T")[0],
        status: "Completed",
        generatedBy: "Current User",
        size: `${(Math.random() * 3 + 1).toFixed(1)} MB`,
      };

      MOCK_REPORTS.push(newReport);
      return newReport;
    }

    return api.post("/reports/generate", reportConfig);
  },

  /**
   * Download report
   * @param {string} id - Report ID
   * @param {string} format - Download format (pdf, csv, excel)
   * @returns {Promise<Blob>} Report file
   */
  async downloadReport(id, format = "pdf") {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 800));

      // Create a mock blob
      const content = `Mock Report Data\nReport ID: ${id}\nFormat: ${format}\nGenerated: ${new Date().toISOString()}`;
      return new Blob([content], { type: `application/${format}` });
    }

    const response = await api.get(`/reports/${id}/download?format=${format}`, {
      headers: { Accept: `application/${format}` },
    });

    return response.blob();
  },

  /**
   * Export report data
   * @param {string} id - Report ID
   * @param {string} format - Export format (csv, json)
   * @returns {Promise<Object>} Export data
   */
  async exportReport(id, format = "csv") {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 600));

      const report = MOCK_REPORTS.find((r) => r.id === id);
      if (!report) throw new Error("Report not found");

      if (format === "csv") {
        const csvData = `Title,Type,Date,Status,Generated By\n${report.title},${report.type},${report.date},${report.status},${report.generatedBy}`;
        return { data: csvData, filename: `${report.title}.csv` };
      }

      return { data: report, filename: `${report.title}.json` };
    }

    return api.get(`/reports/${id}/export?format=${format}`);
  },

  /**
   * Delete report
   * @param {string} id - Report ID
   * @returns {Promise<Object>} Deletion result
   */
  async deleteReport(id) {
    if (USE_MOCK_DATA) {
      await new Promise((resolve) => setTimeout(resolve, 300));

      const index = MOCK_REPORTS.findIndex((r) => r.id === id);
      if (index === -1) throw new Error("Report not found");

      MOCK_REPORTS.splice(index, 1);
      return { success: true, message: "Report deleted successfully" };
    }

    return api.delete(`/reports/${id}`);
  },
};

export default reportsService;
