import React from "react";
import { motion, AnimatePresence } from "framer-motion";
import ProviderLayout from "../layouts/ProviderLayout";

const Reports = () => {
  const [isModalOpen, setIsModalOpen] = React.useState(false);
  const [customConfig, setCustomConfig] = React.useState({
    type: "1",
    startDate: "",
    endDate: "",
  });

  const reports = [
    {
      id: 1,
      title: "High Risk Pregnancy Summary",
      date: "Nov 19, 2025",
      type: "CSV",
      size: "2.4 MB",
    },
    {
      id: 2,
      title: "Monthly Drug Usage Report",
      date: "Nov 01, 2025",
      type: "CSV",
      size: "1.1 MB",
    },
    {
      id: 3,
      title: "Missed Antenatal Appointments",
      date: "Oct 31, 2025",
      type: "CSV",
      size: "856 KB",
    },
    {
      id: 4,
      title: "Quarterly Health Outcomes",
      date: "Oct 15, 2025",
      type: "CSV",
      size: "3.5 MB",
    },
  ];

  const getReportData = (reportId) => {
    switch (parseInt(reportId)) {
      case 1:
        return [
          ["Patient ID", "Risk Factor", "EDD", "Status"],
          ["MS-12345", "Hypertension", "2025-12-01", "Active"],
          ["MS-67890", "Diabetes", "2025-11-20", "Active"],
          ["MS-54321", "Preeclampsia", "2026-01-15", "Admitted"],
        ];
      case 2:
        return [
          ["Drug Name", "Stock", "Used", "Restock Needed"],
          ["Paracetamol", "500", "120", "No"],
          ["Amoxicillin", "200", "45", "No"],
          ["Ibuprofen", "300", "80", "No"],
          ["Folic Acid", "1000", "350", "No"],
          ["Iron Supplements", "800", "200", "No"],
          ["Metformin", "150", "60", "Yes"],
        ];
      case 3:
        return [
          ["Patient Name", "Patient ID", "Missed Date", "Phone Number"],
          ["Amina Okoro", "MS-12345", "2025-11-18", "+234 801 234 5678"],
          ["Fatima Bello", "MS-67890", "2025-11-15", "+234 809 876 5432"],
        ];
      case 4:
        return [
          ["Metric", "Q1", "Q2", "Q3", "Q4"],
          ["Maternal Mortality Rate", "0.05%", "0.04%", "0.03%", "0.02%"],
          ["Neonatal Survival Rate", "98%", "98.5%", "99%", "99.2%"],
          ["C-Section Rate", "15%", "14%", "16%", "15%"],
        ];
      default:
        return [];
    }
  };

  const generateCSV = (report, isCustom = false) => {
    const data = getReportData(report.id);
    const timestamp = new Date().toISOString();
    const reportId =
      Math.random().toString(36).substring(2, 15) +
      Math.random().toString(36).substring(2, 15);
    const signature = btoa(`MAMASAFE-SIG-${report.id}-${timestamp}`);

    const metadata = [
      [],
      ["--- REPORT METADATA ---"],
      ["Generated On", timestamp],
      ["Generated By", "MamaSafe System"],
      ["Report ID", reportId],
      ["Digital Signature", signature],
      ["Verification Status", "Verified & Authentic"],
    ];

    if (isCustom) {
      metadata.push([" Report Type", customConfig.type]);
      metadata.push(["Date Range Start", customConfig.startDate]);
      metadata.push(["Date Range End", customConfig.endDate]);
    }

    metadata.push([]);

    const csvContent = [...data, ...metadata]
      .map((row) => row.join(","))
      .join("\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);

    link.setAttribute("href", url);
    link.setAttribute(
      "download",
      isCustom
        ? `custom_report_${Date.now()}.csv`
        : `${report.title.toLowerCase().replace(/ /g, "_")}.csv`
    );
    link.style.visibility = "hidden";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleDownload = (report) => {
    generateCSV(report);
  };

  const handleCustomGenerate = (e) => {
    e.preventDefault();
    const selectedReport = reports.find(
      (r) => r.id === parseInt(customConfig.type)
    );
    if (selectedReport) {
      generateCSV(selectedReport, true);
      setIsModalOpen(false);
    }
  };

  return (
    <ProviderLayout>
      <div className="max-w-5xl mx-auto relative">
        {/* PageHeading */}
        <motion.header
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
          className="mb-8"
        >
          <h1 className="text-3xl font-black text-gray-900 dark:text-white tracking-tight mb-2">
            Reports
          </h1>
          <p className="text-gray-600 dark:text-gray-400">
            Access and download system reports and analytics.
          </p>
        </motion.header>

        {/* Reports Card */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4, delay: 0.1 }}
          className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm overflow-hidden"
        >
          <div className="p-6 border-b border-gray-200 dark:border-gray-700 flex justify-between items-center">
            <h2 className="text-lg font-bold text-gray-900 dark:text-white">
              Available Reports
            </h2>
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={() => setIsModalOpen(true)}
              className="px-4 py-2 bg-primary/10 text-primary hover:bg-primary/20 rounded-lg text-sm font-medium transition-colors"
            >
              Generate Custom Report
            </motion.button>
          </div>

          {/* Reports List */}
          <motion.div
            initial="hidden"
            animate="visible"
            variants={{
              hidden: { opacity: 0 },
              visible: {
                opacity: 1,
                transition: {
                  staggerChildren: 0.1,
                  delayChildren: 0.2,
                },
              },
            }}
            className="divide-y divide-gray-200 dark:divide-gray-700"
          >
            {reports.map((report) => (
              <motion.div
                key={report.id}
                variants={{
                  hidden: { opacity: 0, x: -20 },
                  visible: { opacity: 1, x: 0 },
                }}
                whileHover={{ scale: 1.01, x: 5 }}
                className="p-6 flex items-center justify-between hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-colors"
              >
                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 rounded-lg bg-gray-100 dark:bg-gray-700 flex items-center justify-center text-gray-500 dark:text-gray-400">
                    <span className="material-symbols-outlined text-2xl">
                      description
                    </span>
                  </div>
                  <div>
                    <h3 className="font-semibold text-gray-900 dark:text-white">
                      {report.title}
                    </h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Generated on {report.date} • {report.type} • {report.size}
                    </p>
                  </div>
                </div>
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  onClick={() => handleDownload(report)}
                  className="flex items-center gap-2 px-4 py-2 border border-gray-200 dark:border-gray-600 rounded-lg text-sm font-medium text-gray-700 dark:text-gray-200 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
                >
                  <span className="material-symbols-outlined text-lg">
                    download
                  </span>
                  Download
                </motion.button>
              </motion.div>
            ))}
          </motion.div>
        </motion.div>

        {/* Custom Report Modal */}
        <AnimatePresence>
          {isModalOpen && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm"
              onClick={() => setIsModalOpen(false)}
            >
              <motion.div
                initial={{ scale: 0.9, y: 20 }}
                animate={{ scale: 1, y: 0 }}
                exit={{ scale: 0.9, y: 20 }}
                onClick={(e) => e.stopPropagation()}
                className="bg-white dark:bg-gray-800 rounded-xl shadow-xl w-full max-w-md p-6 m-4"
              >
                <div className="flex justify-between items-center mb-6">
                  <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                    Generate Custom Report
                  </h3>
                  <motion.button
                    whileHover={{ scale: 1.1 }}
                    whileTap={{ scale: 0.9 }}
                    onClick={() => setIsModalOpen(false)}
                    className="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200"
                  >
                    <span className="material-symbols-outlined">close</span>
                  </motion.button>
                </div>

                <form onSubmit={handleCustomGenerate} className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                      Report Type
                    </label>
                    <select
                      value={customConfig.type}
                      onChange={(e) =>
                        setCustomConfig({
                          ...customConfig,
                          type: e.target.value,
                        })
                      }
                      className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary focus:border-transparent"
                    >
                      {reports.map((report) => (
                        <option key={report.id} value={report.id}>
                          {report.title}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                        Start Date
                      </label>
                      <input
                        type="date"
                        required
                        value={customConfig.startDate}
                        onChange={(e) =>
                          setCustomConfig({
                            ...customConfig,
                            startDate: e.target.value,
                          })
                        }
                        className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary focus:border-transparent"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                        End Date
                      </label>
                      <input
                        type="date"
                        required
                        value={customConfig.endDate}
                        onChange={(e) =>
                          setCustomConfig({
                            ...customConfig,
                            endDate: e.target.value,
                          })
                        }
                        className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary focus:border-transparent"
                      />
                    </div>
                  </div>

                  <div className="flex justify-end gap-3 mt-6">
                    <motion.button
                      whileHover={{ scale: 1.05 }}
                      whileTap={{ scale: 0.95 }}
                      type="button"
                      onClick={() => setIsModalOpen(false)}
                      className="px-4 py-2 text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg font-medium transition-colors"
                    >
                      Cancel
                    </motion.button>
                    <motion.button
                      whileHover={{ scale: 1.05 }}
                      whileTap={{ scale: 0.95 }}
                      type="submit"
                      className="px-4 py-2 bg-primary text-white hover:bg-primary/90 rounded-lg font-medium transition-colors"
                    >
                      Generate
                    </motion.button>
                  </div>
                </form>
              </motion.div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </ProviderLayout>
  );
};

export default Reports;
