import React from "react";
import ProviderLayout from "../layouts/ProviderLayout";

const RiskResult = () => {
  const generateCSV = () => {
    // Medication Safety Check Results Data
    const data = [
      ["MEDICATION SAFETY CHECK RESULTS"],
      [],
      ["Checked Medication", "Drug X, 50mg, twice daily"],
      [],
      ["SAFETY ANALYSIS"],
      ["Category", "Finding", "Status"],
      [
        "Pregnancy Risk Category",
        "Category X - Fetal abnormalities demonstrated",
        "High Risk",
      ],
      [
        "Teratogenic Red Flag",
        "Positive - High risk of structural/functional defects",
        "High Risk",
      ],
      [
        "Breastfeeding Compatibility",
        "Not Recommended - Excreted in human milk",
        "Caution",
      ],
      ["Severe Interactions", "No severe interactions found", "Safe"],
      [],
      ["VERIFIED SAFER ALTERNATIVES"],
      ["Alternative", "Recommendation"],
      ["Alternative A", "Recommended as first-line alternative"],
      ["Alternative B", "Consider if Alternative A is unavailable"],
      ["Alternative C", "Suitable with monitoring"],
    ];

    // Generate Metadata
    const timestamp = new Date().toISOString();
    const reportId =
      Math.random().toString(36).substring(2, 15) +
      Math.random().toString(36).substring(2, 15);
    const signature = btoa(`MAMASAFE-RISK-${timestamp}`);

    const metadata = [
      [],
      ["--- REPORT METADATA ---"],
      ["Generated On", timestamp],
      ["Generated By", "MamaSafe System"],
      ["Report ID", reportId],
      ["Digital Signature", signature],
      ["Verification Status", "Verified & Authentic"],
    ];

    const fullData = [...data, ...metadata];

    const csvContent =
      "data:text/csv;charset=utf-8," +
      fullData.map((e) => e.join(",")).join("\n");

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", "medication_safety_check_results.csv");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <ProviderLayout>
      <div className="max-w-7xl mx-auto">
        {/* PageHeading */}
        <div className="mb-8">
          <p className="text-charcoal dark:text-gray-200 text-4xl font-black leading-tight tracking-[-0.033em]">
            Medication Safety Check Results
          </p>
          <p className="text-gray-500 dark:text-gray-400 mt-1">
            Checked Medication: Drug X, 50mg, twice daily
          </p>
        </div>
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Left Column: Analysis */}
          <div className="lg:col-span-2 flex flex-col gap-6">
            {/* Teratogenic Shield Alert */}
            <div className="bg-white dark:bg-gray-800 rounded-xl shadow-md border-2 border-danger p-6 flex flex-col sm:flex-row items-center gap-6">
              <div className="text-danger">
                <span
                  className="material-symbols-outlined"
                  style={{ fontSize: "80px" }}
                >
                  gpp_bad
                </span>
              </div>
              <div className="text-center sm:text-left">
                <h2 className="text-danger text-2xl font-bold leading-tight tracking-[-0.015em]">
                  TERATOGENIC RISK DETECTED
                </h2>
                <p className="text-charcoal dark:text-gray-300 text-base font-normal leading-normal mt-2">
                  High risk of causing birth defects.{" "}
                  <strong className="font-semibold">
                    Do not administer to pregnant patients.
                  </strong>
                </p>
              </div>
            </div>
            {/* SectionHeader */}
            <h2 className="text-charcoal dark:text-gray-200 text-[22px] font-bold leading-tight tracking-[-0.015em] pt-2">
              Safety Analysis
            </h2>
            {/* Analysis List */}
            <div className="bg-white dark:bg-gray-800 rounded-xl shadow-md divide-y divide-gray-200 dark:divide-gray-700">
              {/* ListItem: Pregnancy Risk */}
              <div className="flex items-center gap-4 px-6 min-h-[72px] py-4 justify-between">
                <div className="flex items-center gap-4">
                  <div className="text-danger flex items-center justify-center rounded-lg bg-danger/10 shrink-0 size-12">
                    <span className="material-symbols-outlined text-3xl">
                      pregnant_woman
                    </span>
                  </div>
                  <div className="flex flex-col justify-center">
                    <p className="text-charcoal dark:text-white text-base font-medium leading-normal">
                      Pregnancy Risk Category
                    </p>
                    <p className="text-gray-600 dark:text-gray-400 text-sm font-normal leading-normal">
                      Category X - Studies in animals or humans have
                      demonstrated fetal abnormalities.
                    </p>
                  </div>
                </div>
                <div className="shrink-0">
                  <div className="flex items-center justify-center">
                    <div className="size-4 rounded-full bg-danger"></div>
                  </div>
                </div>
              </div>
              {/* ListItem: Teratogenic Red Flag */}
              <div className="flex items-center gap-4 px-6 min-h-[72px] py-4 justify-between">
                <div className="flex items-center gap-4">
                  <div className="text-danger flex items-center justify-center rounded-lg bg-danger/10 shrink-0 size-12">
                    <span className="material-symbols-outlined text-3xl">
                      error
                    </span>
                  </div>
                  <div className="flex flex-col justify-center">
                    <p className="text-charcoal dark:text-white text-base font-medium leading-normal">
                      Teratogenic Red Flag
                    </p>
                    <p className="text-gray-600 dark:text-gray-400 text-sm font-normal leading-normal">
                      Positive - High risk of causing structural or functional
                      defects in the embryo or fetus.
                    </p>
                  </div>
                </div>
                <div className="shrink-0">
                  <div className="flex items-center justify-center">
                    <div className="size-4 rounded-full bg-danger"></div>
                  </div>
                </div>
              </div>
              {/* ListItem: Breastfeeding */}
              <div className="flex items-center gap-4 px-6 min-h-[72px] py-4 justify-between">
                <div className="flex items-center gap-4">
                  <div className="text-warning flex items-center justify-center rounded-lg bg-warning/10 shrink-0 size-12">
                    <span className="material-symbols-outlined text-3xl">
                      breastfeeding
                    </span>
                  </div>
                  <div className="flex flex-col justify-center">
                    <p className="text-charcoal dark:text-white text-base font-medium leading-normal">
                      Breastfeeding Compatibility
                    </p>
                    <p className="text-gray-600 dark:text-gray-400 text-sm font-normal leading-normal">
                      Not Recommended - Drug is known to be excreted in human
                      milk and may pose risk.
                    </p>
                  </div>
                </div>
                <div className="shrink-0">
                  <div className="flex items-center justify-center">
                    <div className="size-4 rounded-full bg-warning"></div>
                  </div>
                </div>
              </div>
              {/* ListItem: Interactions */}
              <div className="flex items-center gap-4 px-6 min-h-[72px] py-4 justify-between">
                <div className="flex items-center gap-4">
                  <div className="text-safe flex items-center justify-center rounded-lg bg-safe/10 shrink-0 size-12">
                    <span className="material-symbols-outlined text-3xl">
                      medication
                    </span>
                  </div>
                  <div className="flex flex-col justify-center">
                    <p className="text-charcoal dark:text-white text-base font-medium leading-normal">
                      Severe Interactions
                    </p>
                    <p className="text-gray-600 dark:text-gray-400 text-sm font-normal leading-normal">
                      No severe interactions found with the patient's current
                      medication list.
                    </p>
                  </div>
                </div>
                <div className="shrink-0">
                  <div className="flex items-center justify-center">
                    <div className="size-4 rounded-full bg-safe"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* Right Column: Alternatives & Actions */}
          <div className="lg:col-span-1 flex flex-col gap-6">
            {/* Alternative Medications Panel */}
            <div className="bg-white dark:bg-gray-800 rounded-xl shadow-md p-6">
              <h3 className="text-primary text-xl font-bold leading-tight tracking-[-0.015em]">
                Verified Safer Alternatives
              </h3>
              <p className="text-gray-500 dark:text-gray-400 text-sm mt-1 mb-4">
                The following medications are verified as safer for use in
                pregnancy.
              </p>
              <div className="space-y-3">
                {/* Alternative Card */}
                <div className="border border-gray-200 dark:border-gray-700 rounded-lg p-4 cursor-pointer hover:border-primary hover:bg-primary/5 dark:hover:bg-primary/10 transition-all">
                  <p className="font-bold text-charcoal dark:text-white">
                    Alternative A
                  </p>
                  <p className="text-sm text-gray-600 dark:text-gray-400">
                    Recommended as first-line alternative.
                  </p>
                </div>
                {/* Alternative Card */}
                <div className="border border-gray-200 dark:border-gray-700 rounded-lg p-4 cursor-pointer hover:border-primary hover:bg-primary/5 dark:hover:bg-primary/10 transition-all">
                  <p className="font-bold text-charcoal dark:text-white">
                    Alternative B
                  </p>
                  <p className="text-sm text-gray-600 dark:text-gray-400">
                    Consider if Alternative A is unavailable.
                  </p>
                </div>
                {/* Alternative Card */}
                <div className="border border-gray-200 dark:border-gray-700 rounded-lg p-4 cursor-pointer hover:border-primary hover:bg-primary/5 dark:hover:bg-primary/10 transition-all">
                  <p className="font-bold text-charcoal dark:text-white">
                    Alternative C
                  </p>
                  <p className="text-sm text-gray-600 dark:text-gray-400">
                    Suitable with monitoring.
                  </p>
                </div>
              </div>
            </div>
            {/* Action Buttons Panel */}
            <div className="bg-white dark:bg-gray-800 rounded-xl shadow-md p-6">
              <h3 className="text-charcoal dark:text-white text-xl font-bold leading-tight tracking-[-0.015em] mb-4">
                Actions
              </h3>
              <div className="flex flex-col space-y-3">
                <button className="flex w-full items-center justify-center gap-2 rounded-lg bg-primary px-4 py-3 text-base font-bold text-white shadow-sm hover:bg-primary/90">
                  <span className="material-symbols-outlined">
                    playlist_add_check
                  </span>
                  Select Alternative
                </button>
                <button
                  onClick={generateCSV}
                  className="flex w-full items-center justify-center gap-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 px-4 py-3 text-base font-bold text-charcoal dark:text-white shadow-sm hover:bg-gray-50 dark:hover:bg-gray-600"
                >
                  <span className="material-symbols-outlined">print</span>
                  Print / Save Report
                </button>
                <button className="flex w-full items-center justify-center gap-2 rounded-lg border border-transparent bg-transparent px-4 py-3 text-base font-bold text-danger hover:bg-danger/10">
                  <span className="material-symbols-outlined">warning</span>
                  Acknowledge & Override
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </ProviderLayout>
  );
};

export default RiskResult;
